sudo: false

language: python

python:
  - "2.7"
  - "3.4"

env:
  - MODE=flake8
  - MODE=flake8-strict
  - MODE=docs
  - DJANGO_VERSION=dj18
  - DJANGO_VERSION=dj111
  - DJANGO_VERSION=djdev

matrix:
  allow_failures:
    - env: DJANGO_VERSION=djdev
    - env: MODE=flake8-strict
  exclude:
    - python: "3.4"
      env: MODE=flake8
    - python: "3.4"
      env: MODE=flake8-strict

addons:
  apt:
    packages:
    - binutils
    - libproj-dev
    - gdal-bin
    - spatialite-bin
    - libspatialite-dev

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# command to install dependencies
install:
    - pip install -U pip
    - pip install -U wheel virtualenv
    - pip install tox coveralls

after_success:
    - coveralls

# command to run tests
script:
    - coverage erase
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION}${MODE}
